### ISSUE TITLE
Lecture 9 / Slide 16 text doesn't fit inside

### ISSUE THREAD

**Issue by IAmWave** [ufal/npfl122#14]
[Please see screenshot.](https://screenshots.firefox.com/JGzHDbp4PtfEM4NT/ufal.mff.cuni.cz) Resizing doesn't seem to help as the presentation keeps a fixed aspect ratio.

**Comment by foxik** [comment]
The second line fit when viewing in Firefox, and, strangely, it also fit when using Chromium on my local slide repo (but not when using the same browser on the UFAL url). Nevertheless, I made the second line a bit thinner and it seems to fit on all my browsers now.
