### ISSUE TITLE
Parameter to change for UCB in MultiArmedBandits seems wrong

### ISSUE THREAD

**Issue by IAmWave** [ufal/npfl122#2]
> ucb: perform UCB search with confidence level c and computing the value function using averaging. Plot results for c=1 and ε∈{1/128,1/64,1/32,1/16,1/8}

But according to the slides, the ε parameter is not used at all in UCB, as we replace the ε-greedy strategy with an argmax. Perhaps we should be changing c?

**Comment by foxik** [comment]
You are right, of course. I had an error in the solution, which produced different results for different ε, which masked the problem in the description.

I changed the description so that `c` should take values in {1/4, 1/2, 1, 2, 4}.
