### ISSUE TITLE
TD errors definitions +-1 error

### ISSUE THREAD

**Issue by JanKaifer** [ufal/npfl122#55]
Behem delani ulohy `tarce_algorithms` jsem narazil na nasledujici nejasnost:

![Screenshot from 2022-02-07 00-43-17](https://user-images.githubusercontent.com/12820484/152706688-410f20ca-c443-40d5-8c14-e54b0c515a28.png)
[zdroj definice](https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?09#5)

Myslim, ze tam misto `R_{t+1}` ma byt `R_i`

Ale kdyz si dany vzorecek dosadim do sum z [prehledu](https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?09#26)
Tak mi vychazi zohlednene rewards o jedna posunute.

Na piazze zminujete nasledujici:
> If an episode ends, only the value function of the V(next_state) “after the episode” is not used; all other value functions in TD errors are computed. So all TD errors are unchanged, except for the last one, which is just R_T - V(S_T)

[zdroj citace](https://piazza.com/class/kucekm98b3z1mt?cid=191) Coz neodpovida slidum.

Cekal bych, ze `R_t` a `V_t` budou vynasobene stejnou mocninou gammy.

EDIT: Klidne vyrobim PR, jenom jsem si chtel nejdrive overit, ze to je opravdu spatne.

**Comment by foxik** [comment]
Pokud dobře koukám, tak jediná chyba je v mé odpovědi na Piazze -- tj. TD chyba v čase T (koncový čas episody, tj. po provedení akce A_T jsem dostal R_{T+1}, done=True, a S_{T+1} už je "nevalidní" stav) má být R_{T+1} - V(S_T), tj. chybí tam to gamma * V(S_{T+1}).

Jinak mi to přijde, že definice TD chyby na https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?08#56 a https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?09#5 je v pořádku (tj. pro delta_t je tam R_{t+1}), protože pak třeba v prvním vzorečku na https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?09#26 vyjde G_{t:t+n} jako V(S_t) + gamma^0 (R_{t+1} + gamma * V(S_{t+1}) - V(S_t)) + gamma^1 (R_{t+2} + gamma * V(S_{t+2}) - V(S_{t+1})) + ..., což po odstranění hodnot, které se přičítají a odečítají, dá R_{t+1} + gamma R_{t+2} + gamma^2 R_{t+3} + ... + gamma^n V(S_{t+n}), což je konzistentní s https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?08#53 i s https://ufal.mff.cuni.cz/~straka/courses/npfl122/2122/slides/?03#89 .

Pokud něco přehlížím (což se může lehce stát), tak se mě neváhejte opravit ;-) A omlouvám se za ten chybný index u R v odpovědi na Piazze...

**Comment by JanKaifer** [comment]
Díky moc za dovysvětlení. Slajdy mi přišly konzistentní.
Nedošlo mi, že mám posunuté indexování.

Problém byl v tom, že v mém kódu používám posunuté indexování  ve stavu `state[i]` po vykonání `action[i]` dostanu `reward[i]`.

A náhodou se to shodovalo s překlepem na Piazze (takže potenciálně s kódem, který jste opravoval).
