### ISSUE TITLE
Non-matching types

### ISSUE THREAD

**Issue by Reblexis** [ufal/npfl122#64]
There are non-matching types in [policy_iteration_mc_egreedy.py](https://github.com/ufal/npfl122/blob/master/labs/02/policy_iteration_mc_egreedy.py). Main function is supposed to return "list[int]", instead returns "np.ndarray".

**Comment by foxik** [comment]
Hi,

you are right. Actually, all `policy_iteration*` assignments can return both lists or numpy arrays.

Unfortunately, there is not a single type that could describe that (the ArrayLike https://numpy.org/devdocs/reference/typing.html#numpy.typing.ArrayLike is close, but it is not generic, i.e., you cannot say `ArrayLike[int]`). Therefore, in c3f5220c1c36 I explicitly wrote `Union[list[float], np.ndarray]`. Once we start using Python 3.10, we will be able to simplify to just `list[float] | np.ndarray`.

A community-work point is yours :-)
