### ISSUE TITLE
S^+ not explained in code

### ISSUE THREAD

**Issue by Karryanna** [ufal/npfl122#7]
In code for value iteration (lec 2, slide 11) and Sarsa (lec 3, slide 13), S^+ is used but not explained. Does it stand for reachable states only? (And could that be written on the slides? :))

**Comment by foxik** [comment]
It is a notation I did not explain on the lectures (S+ means all non-terminal states; it is a required formalism for unifying both terminating and non-terminating episodes). I removed all S+ in the slides (there were several more). Thanks!
