### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by simonmandlik** [ufal/npfl122#80]
In Lecture 4, slides 18 and 19, shouldn't we initialize **action**-value-function weights instead of just value-function weights?

**Comment by foxik** [comment]
Hi,

thanks! Yes, they are action-value function weights; in the Reinforcement learning book, the authors sometimes use "value function" to refer both to v and q, and use "state-value function" when they want to explicitly mention v. And the algorithms are taken directly from the book.

Keeping open until I find time to fix them.

**Comment by Fassty** [comment]
> Keeping open until I find time to fix them.

I found some time to do that :)

**Comment by foxik** [comment]
Also, that is a community-work to the reporter as well :-)
